### ISSUE TITLE
Exposed credentials

### ISSUE THREAD

**Issue by chriscoffee** [sayeem88/CurrencyPairs#1]
Hey @sayeem88 just a random message from a stranger checking that you know some credentials have been commited https://github.com/sayeem88/CurrencyPairs/blob/ce2c20349f2c9697dcd09842b417c2ce8dc03d02/fastlane/Appfile

Might be worth making these environment variables and changing your keys :+1:

**Comment by sayeem88** [comment]
Thanks for looking out @chriscoffee the token was revoked.
